/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockEERC20Bridge__factory } from "./MockEERC20Bridge__factory";
export { MockERC20__factory } from "./MockERC20__factory";
